In [1]:
import numpy as np

I = np.array([[1,-3,3],[3,-5,3],[6,-6,4]])
print("\nGiven Matrix: \n", I)

w,v = np.linalg.eig(I)
print("\nEigen Values: \n",w)
print("\nEigen Vectors: \n",v)


Given Matrix: 
 [[ 1 -3  3]
 [ 3 -5  3]
 [ 6 -6  4]]

Eigen Values: 
 [ 4. -2. -2.]

Eigen Vectors: 
 [[ 0.40824829 -0.40824829 -0.30502542]
 [ 0.40824829  0.40824829 -0.808424  ]
 [ 0.81649658  0.81649658 -0.50339858]]
