In [5]:
import numpy as np

I = np.array([[4,3,2],[1,4,1],[3,10,4]])
print("\nGiven Matrix: \n", I)

w,v = np.linalg.eig(I)
print("\nEigen Values: \n",w)
print("\nEigen Vectors: \n",v)

print("\nEigen Value: \n", w[0])
print("\nCorresponding Eigen Vector: \n", v[:,0])


Given Matrix: 
 [[ 4  3  2]
 [ 1  4  1]
 [ 3 10  4]]

Eigen Values: 
 [8.98205672 2.12891771 0.88902557]

Eigen Vectors: 
 [[-0.49247712 -0.82039552 -0.42973429]
 [-0.26523242  0.14250681 -0.14817858]
 [-0.82892584  0.55375355  0.89071407]]

Eigen Value: 
 8.982056720677651

Corresponding Eigen Vector: 
 [-0.49247712 -0.26523242 -0.82892584]
